### PR TITLE
Add license information to the package

### PR DESCRIPTION
**Pull request by lazka**
Further information:

* https://getcomposer.org/doc/04-schema.md#license
* https://spdx.org/licenses/CECILL-2.0.html
* https://spdx.org/licenses/GPL-3.0-or-later.html

### CODE REVIEW

**Comment by lazka** [comment]
ping

**Comment by walva** [comment]
FYI: https://opensource.guide/legal/
It would be nice to have a license indeed :)

**Comment by walva** [comment]
BTW, I would prefer MIT over GNU. In my case, if the package is GNU, I won't using in my professionals projects.

**Comment by lazka** [comment]
> BTW, I would prefer MIT over GNU. In my case, if the package is GNU, I won't using in my professionals projects.

This package already has a license, it is just missing in the composer meta data.

**Comment by walva** [comment]
Thx for the info, I wasn't aware of this!

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
